# Generated by Django 5.1.3 on 2025-12-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="video",
        ),
        migrations.AddField(
            model_name="lesson",
            name="video",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
