# Generated by Django 5.2.7 on 2025-12-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_video_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=0, help_text='Thời lượng bài học'),
        ),
    ]
