# Generated by Django 5.2.7 on 2026-01-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MOMO', 'MoMo'), ('ZALOPAY', 'ZaloPay'), ('PAYPAL', 'PayPal')], default='MOMO', max_length=20),
        ),
    ]
