# Generated by Django 5.2.7 on 2026-01-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Completed')], default='1', max_length=20),
        ),
    ]
