# Generated by Django 5.2.7 on 2026-01-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MOMO', 'MoMo'), ('ZALOPAY', 'ZaloPay'), ('VNPAY', 'VNPay')], default='MOMO', max_length=20),
        ),
    ]
