# Generated by Django 5.2.7 on 2026-01-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.IntegerField(default=0, help_text="Tổng thời lượng khóa học"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("1", "Pending"), ("2", "Completed"), ("3", "Failed")],
                default="1",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
