# Generated by Django 5.2.7 on 2026-01-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_course_duration_alter_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
